# Generated by Django 5.0.4 on 2024-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
